In [72]:
import pandas as pd
import numpy as np
movies = pd.read_csv("tmdb_5000_movies.csv")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [73]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [74]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [75]:
credits = pd.read_csv("tmdb_5000_credits.csv")
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [76]:
movies = pd.merge(movies, credits, on="title", how='outer')

movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,7500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://500days.com,19913,"[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...",en,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...",45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,15000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...",http://www.10cloverfieldlane.com/,333371,"[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...",en,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...",53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,1200000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,345003,"[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...",en,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ...",0.489271,[],...,111.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,10 Days in a Madhouse,4.3,5,345003,"[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,16000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,4951,"[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...",en,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da...",54.550275,"[{""name"": ""Mad Chance"", ""id"": 1757}, {""name"": ...",...,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,How do I loathe thee? Let me count the ways.,10 Things I Hate About You,7.3,1701,4951,"[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."

In [77]:
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

In [78]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."

In [79]:
movies['crew'][0]

'[{"credit_id": "545bbac70e0a261fb6002329", "department": "Writing", "gender": 1, "id": 61111, "job": "Screenplay", "name": "Tara Subkoff"}, {"credit_id": "545bbabf0e0a261fb9002212", "department": "Directing", "gender": 1, "id": 61111, "job": "Director", "name": "Tara Subkoff"}, {"credit_id": "545bbae4c3a36853500018a8", "department": "Production", "gender": 1, "id": 61111, "job": "Producer", "name": "Tara Subkoff"}, {"credit_id": "545bbad3c3a3685358001b92", "department": "Production", "gender": 0, "id": 1382445, "job": "Producer", "name": "Jason Ludman"}, {"credit_id": "545bbadbc3a368535d001e74", "department": "Production", "gender": 0, "id": 1382446, "job": "Producer", "name": "Oren Segal"}, {"credit_id": "545bbaf3c3a3685358001b9d", "department": "Production", "gender": 0, "id": 1382448, "job": "Producer", "name": "Brendan Walsh"}]'

In [80]:
movies['cast'][0]

'[{"cast_id": 0, "character": "Alex\'s 12-Step Friend", "credit_id": "545bba84c3a3685358001b80", "gender": 1, "id": 343, "name": "Taryn Manning", "order": 1}, {"cast_id": 1, "character": "Sam\'s Mom", "credit_id": "545bba8a0e0a261fad0023f6", "gender": 1, "id": 10871, "name": "Natasha Lyonne", "order": 2}, {"cast_id": 2, "character": "Alex Cox", "credit_id": "545bba8fc3a36853500018a4", "gender": 1, "id": 2838, "name": "Chlo\\u00eb Sevigny", "order": 3}, {"cast_id": 3, "character": "Mr. Cox", "credit_id": "545bba94c3a3685353001a56", "gender": 2, "id": 9296, "name": "Balthazar Getty", "order": 4}, {"cast_id": 4, "character": "Dr. White", "credit_id": "545bba990e0a261fb900220b", "gender": 2, "id": 16327, "name": "Timothy Hutton", "order": 5}, {"cast_id": 5, "character": "Lisa", "credit_id": "545bba9ec3a368535d001e67", "gender": 1, "id": 210573, "name": "Lydia Hearst", "order": 6}, {"cast_id": 6, "character": "Mom", "credit_id": "545bbaa4c3a368535d001e6b", "gender": 0, "id": 180425, "name": "Jessica Blank", "order": 7}, {"cast_id": 7, "character": "Molly", "credit_id": "545bbab1c3a3685362001a0f", "gender": 0, "id": 1102331, "name": "Annabelle Dexter-Jones", "order": 8}, {"cast_id": 15, "character": "Tatiana (voice)", "credit_id": "572f9a8792514102ac000642", "gender": 1, "id": 61111, "name": "Tara Subkoff", "order": 9}]'

In [81]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [82]:
import ast
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [83]:
movies['crew']=movies['crew'].apply(fetch_director)

In [84]:
import ast
def fetch_crew(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['character'])
        
    return L

In [85]:
movies['cast']=movies['cast'].apply(fetch_crew)

In [86]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[Alex's 12-Step Friend, Sam's Mom, Alex Cox, M...",[Tara Subkoff]

In [87]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [88]:
movies.dropna(inplace=True)

In [89]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[Drama, Mystery, Horror, Thriller]",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[Alex's 12-Step Friend, Sam's Mom, Alex Cox, M...",[Tara Subkoff]
1,7500000,"[Comedy, Drama, Romance]",http://500days.com,19913,"[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...",en,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...",45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"[Tom Hansen, Summer Finn, Rachel Hansen, McKen...",[Marc Webb]
2,15000000,"[Thriller, Science Fiction, Drama]",http://www.10cloverfieldlane.com/,333371,"[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...",en,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...",53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"[Michelle, Howard Stambler, Emmett DeWitt, Ben...",[Dan Trachtenberg]
9,20000000,"[Action, Adventure, Drama, Thriller]",http://www.12rounds-movie.com/,17134,"[{""id"": 6149, ""name"": ""police""}, {""id"": 8233, ...",en,12 Rounds,When New Orleans cop Danny Fisher prevents a b...,15.661350,"[{""name"": ""The Mark Gordon Company"", ""id"": 155...",...,108.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,Survive all 12,12 Rounds,5.7,220,17134,"[Det. Danny Fisher, Miles Jackson, Molly Porte...",[Renny Harlin]
13,50000000,"[Action, Drama, History, Thriller, War]",http://www.thirteenhoursmovie.com/,300671,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,13 Hours: The Secret Soldiers of Benghazi,An American Ambassador is killed during an att...,42.526529,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,144.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,"When everything went wrong, six men had the co...",13 Hours: The Secret Soldiers of Benghazi,7.0,938,300671,"[Tyrone 'Rone' Woods, Jack Silva, Mark 'Oz' Ge...",[Michael Bay]

In [90]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[Drama, Mystery, Horror, Thriller]",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[Alex's 12-Step Friend, Sam's Mom, Alex Cox, M...",[Tara Subkoff]
1,7500000,"[Comedy, Drama, Romance]",http://500days.com,19913,"[date, sex, jealousy, fight, architect, galler...",en,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...",45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"[Tom Hansen, Summer Finn, Rachel Hansen, McKen...",[Marc Webb]
2,15000000,"[Thriller, Science Fiction, Drama]",http://www.10cloverfieldlane.com/,333371,"[kidnapping, bunker, paranoia, basement, survi...",en,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...",53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"[Michelle, Howard Stambler, Emmett DeWitt, Ben...",[Dan Trachtenberg]
9,20000000,"[Action, Adventure, Drama, Thriller]",http://www.12rounds-movie.com/,17134,"[police, cops, cat and mouse, family, revenge ...",en,12 Rounds,When New Orleans cop Danny Fisher prevents a b...,15.661350,"[{""name"": ""The Mark Gordon Company"", ""id"": 155...",...,108.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,Survive all 12,12 Rounds,5.7,220,17134,"[Det. Danny Fisher, Miles Jackson, Molly Porte...",[Renny Harlin]
13,50000000,"[Action, Drama, History, Thriller, War]",http://www.thirteenhoursmovie.com/,300671,"[based on novel, assault rifle, mercenary, lib...",en,13 Hours: The Secret Soldiers of Benghazi,An American Ambassador is killed during an att...,42.526529,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,144.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,"When everything went wrong, six men had the co...",13 Hours: The Secret Soldiers of Benghazi,7.0,938,300671,"[Tyrone 'Rone' Woods, Jack Silva, Mark 'Oz' Ge...",[Michael Bay]

In [91]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [92]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [93]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[Drama, Mystery, Horror, Thriller]",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[Alex's12-StepFriend, Sam'sMom, AlexCox, Mr.Co...",[TaraSubkoff]
1,7500000,"[Comedy, Drama, Romance]",http://500days.com,19913,"[date, sex, jealousy, fight, architect, galler...",en,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...",45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",...,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"[TomHansen, SummerFinn, RachelHansen, McKenzie...",[MarcWebb]
2,15000000,"[Thriller, ScienceFiction, Drama]",http://www.10cloverfieldlane.com/,333371,"[kidnapping, bunker, paranoia, basement, survi...",en,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...",53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"[Michelle, HowardStambler, EmmettDeWitt, Ben(v...",[DanTrachtenberg]
9,20000000,"[Action, Adventure, Drama, Thriller]",http://www.12rounds-movie.com/,17134,"[police, cops, catandmouse, family, revengedrama]",en,12 Rounds,When New Orleans cop Danny Fisher prevents a b...,15.661350,"[{""name"": ""The Mark Gordon Company"", ""id"": 155...",...,108.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,Survive all 12,12 Rounds,5.7,220,17134,"[Det.DannyFisher, MilesJackson, MollyPorter, S...",[RennyHarlin]
13,50000000,"[Action, Drama, History, Thriller, War]",http://www.thirteenhoursmovie.com/,300671,"[basedonnovel, assaultrifle, mercenary, libya,...",en,13 Hours: The Secret Soldiers of Benghazi,An American Ambassador is killed during an att...,42.526529,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,144.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,"When everything went wrong, six men had the co...",13 Hours: The Secret Soldiers of Benghazi,7.0,938,300671,"[Tyrone'Rone'Woods, JackSilva, Mark'Oz'Geist, ...",[MichaelBay]

In [94]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [95]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [96]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [97]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,budget,homepage,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,tags
0,1500000,http://www.hashtaghorror.com/,301325,de,#Horror,2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-11-20,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"Inspired by actual events, a group of 12 year ..."
1,7500000,http://500days.com,19913,en,(500) Days of Summer,45.610993,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-07-17,60722734,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It was almost like falling in love.,(500) Days of Summer,7.2,2904,19913,"Tom (Joseph Gordon-Levitt), greeting-card writ..."
2,15000000,http://www.10cloverfieldlane.com/,333371,en,10 Cloverfield Lane,53.698683,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-10,108286421,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Monsters come in many forms.,10 Cloverfield Lane,6.8,2468,333371,"After a car accident, Michelle awakens to find..."
9,20000000,http://www.12rounds-movie.com/,17134,en,12 Rounds,15.661350,"[{""name"": ""The Mark Gordon Company"", ""id"": 155...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-03-19,17280326,108.0,"[{""iso_639_1"": ""cs"", ""name"": ""\u010cesk\u00fd""...",Released,Survive all 12,12 Rounds,5.7,220,17134,When New Orleans cop Danny Fisher prevents a b...
13,50000000,http://www.thirteenhoursmovie.com/,300671,en,13 Hours: The Secret Soldiers of Benghazi,42.526529,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""MT"", ""name"": ""Malta""}, {""iso_...",2016-01-13,69411370,144.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,"When everything went wrong, six men had the co...",13 Hours: The Secret Soldiers of Benghazi,7.0,938,300671,An American Ambassador is killed during an att...

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [99]:
vector = cv.fit_transform(new['tags']).toarray()

In [100]:
vector.shape

(1494, 5000)

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

In [102]:
similarity = cosine_similarity(vector)

In [103]:
similarity

array([[1.        , 0.03651484, 0.06073322, ..., 0.13801311, 0.02936101,
        0.06642112],
       [0.03651484, 1.        , 0.01478443, ..., 0.        , 0.        ,
        0.01616904],
       [0.06073322, 0.01478443, 1.        , ..., 0.02793994, 0.07132756,
        0.0358575 ],
       ...,
       [0.13801311, 0.        , 0.02793994, ..., 1.        , 0.08104409,
        0.06111323],
       [0.02936101, 0.        , 0.07132756, ..., 0.08104409, 1.        ,
        0.13001274],
       [0.06642112, 0.01616904, 0.0358575 , ..., 0.06111323, 0.13001274,
        1.        ]], shape=(1494, 1494))

In [104]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(3923)

In [117]:
new["title"].head()

0                                       #Horror
1                          (500) Days of Summer
2                           10 Cloverfield Lane
9                                     12 Rounds
13    13 Hours: The Secret Soldiers of Benghazi
Name: title, dtype: object

In [135]:
import pandas as pd
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ✅ Step 1: Reset index (VERY IMPORTANT)
new = new.reset_index(drop=True)

# ✅ Step 2: Vectorization
cv = CountVectorizer(max_features=5000, stop_words='english')
vector = cv.fit_transform(new['tags']).toarray()

# ✅ Step 3: Similarity
similarity = cosine_similarity(vector)


# ✅ Step 4: Recommend Function (FIXED)
def recommend(movie):
    movie = movie.lower()  # handle case issue
    
    # create lowercase title column temporarily
    new['title_lower'] = new['title'].str.lower()
    
    if movie not in new['title_lower'].values:
        print("❌ Movie not found in dataset")
        return
    
    index = new[new['title_lower'] == movie].index[0]
    
    distances = list(enumerate(similarity[index]))
    distances = sorted(distances, reverse=True, key=lambda x: x[1])
    
    print(f"\n🎬 Recommendations for '{movie.title()}':\n")
    
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)


# ✅ Test
recommend('Gandhi')


# ✅ Step 5: Save both files
pickle.dump(new, open('movie_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

❌ Movie not found in dataset

In [136]:
# def recommend(movie):
#     index = new[new['title']] == movie.index[0]
#     distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
#     for i in distances[1:6]:
#         print(new.iloc[i[0]].title)

In [137]:
recommend('#Horror')

🎬 Recommendations for '#Horror':

The Exorcist
The Unborn
Donkey Punch
Mama
One Missed Call

In [138]:
#df[df['title'].isin(['#Horror', '(500) Days of Summer'])]

In [ ]:
#movie_index = df[df['title'] == '(500) Days of Summer'].index[0]

In [141]:
#movies.shape

In [142]:
#new.shape

In [139]:
# movie_index = new[new['title'] == movies].index[0]
# distances = similarity[movie_index]

In [143]:

#import pickle

In [ ]:
# pickle.dump(new,open('movie_list.pkl','wb'))
# pickle.dump(similarity,open('similarity.pkl','wb'))

In [140]:
#movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]